"""
This type stub file was generated by pyright.
"""

from typing import Tuple, Union

TYPE_CHECKING = ...
if TYPE_CHECKING:
    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    ...
version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
version = ...
version_tuple = ...
